### ISSUE TITLE
Example videos not playing on mobile.

### ISSUE THREAD

**Issue by AlexanderChernyshev** [Speed-Patterns/speed-patterns#36]
Need to find a way to write them to be able to play on mobile devices.

Can try adding "playsinline".

Otherwise this article might have answers: https://medium.com/@BoltAssaults/autoplay-muted-html5-video-safari-ios-10-in-react-673ae50ba1f5

**Comment by AlexanderChernyshev** [comment]
Should have been fixed. Added autoplay to attributes, and it seems to have made them play on mobile.

**Comment by sergeychernyshev** [comment]
Where's the code for this fix? did you create a PR for it?
